#启动: nohup java  -jar  xxx.jar >  log.admin 2>&1 &
server:
  port: 8088
  compression:
    enabled: true
  connection-timeout: 3000
spring:
#  redis:
#      host: 192.168.0.128
#      port: 6380
  datasource:
      url: jdbc:mysql://localhost:3306/gaily?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 654321
      driverClassName : com.mysql.cj.jdbc.Driver
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
mybatis:
  mapperLocations: classpath:mapper/*.xml
#logging:
#  level:
#    com:
#      enjoy:
#        dao:  debug



